# Generated by Django 6.0.2 on 2026-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clean_ingreds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
